permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 丁一鸣
  email: vimdingyiming@qq.com
  link: http://dingyiming.github.io
  weibo: http://weibo.com/vimdingyiming
  github: http://github.com/dingyiming

# 站点信息
title: 丁一鸣
description: 丁一鸣的博客
url: http://dingyiming.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: dingyiming.github.io

# disqus 设置
disqus:
  shortname: dingyiming